backend:
  replicas: 1
  port: "8080"

  service:
    type: LoadBalancer
    port: 8008

  image:
    repository: aliasboink/testing
    pullPolicy: Always
    tag: "agg-1"

frontend:
  replicas: 1
  image:
    repository: aliasboink/testing
    pullPolicy: Always
    tag: "fe-1"

  service:
    type: LoadBalancer
    port: 3000

nameOverride: ""
fullnameOverride: ""

