backend:
  replicas: 1
  port: "8080"

  service:
    type: LoadBalancer
    port: 8008

  image:
    repository: aliasboink/rss-aggregator-stripped
    pullPolicy: Always
    tag: "backend-v0.0.2"

frontend:
  replicas: 1
  image:
    repository: aliasboink/rss-aggregator-stripped
    pullPolicy: Always
    tag: "frontend-v0.0.1"

  service:
    type: LoadBalancer
    port: 3000

nameOverride: ""
fullnameOverride: ""

