apiVersion: v2
appVersion: 1.20.5
name: rpi-gitea
version: 1.0.0
description: Gitea official chart.
type: application 
dependencies:
  - name: gitea-charts/gitea
    version: 1.0.6
    repository: https://dl.gitea.com/charts/