apiVersion: v1
kind: Endpoints
metadata:
  name: postgresql
subsets:
- addresses:
  - ip: <ip-where-postgresql-is-hosted> # Local network IP address 192.168.1.53 (for instance)
  ports:
  - port: 5432
    protocol: TCP
