apiVersion: v1
kind: Secret
metadata:
  name: gitea-postgresql-credentials
type: Opaque
data:
  host: <base64-encoded-GITEA__DATABASE__HOST>
  password: <base64-encoded-GITEA__DATABASE__PASSWD>
  dbname: <base64-encoded-GITEA__DATABASE__NAME>
  user: <base64-encoded-GITEA__DATABASE__USER>
