apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: default
  finalizers:
    - resources-finalizer.gitea.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: helm_charts/gitea
    repoURL: git@github.com:aliasboink/raspberrypi_argocd_charts.git
    targetRevision: main
    helm:
      valueFiles: 
        - ../helm_charts/gitea/values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true