apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.prometheus.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      valueFiles:
      - $valuesRepo/values/values-kube-prometheus-stack.yaml
  - repoURL: 'https://github.com/aliasboink/raspberrypi_argocd_charts'
    targetRevision: main
    ref: valuesRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
