apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agg
  namespace: argocd
  finalizers:
    - resources-finalizer.rss-aggregator.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rss-aggregator
  project: default
  sources:
  - repoURL: 'https://github.com/aliasboink/go_rss_aggregator_stripped_helm_chart'
    path: ./
    targetRevision: 'v0.0.3'
    helm:
      valueFiles:
      - $valuesRepo/values/values-rss-aggregator.yaml
  - repoURL: 'https://github.com/aliasboink/raspberrypi_argocd_charts'
    targetRevision: main
    ref: valuesRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
